config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    resources :reviews, only: [ :new, :create, :update, :destroy, :edit ]
  end
end

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
#          Prefix Verb   URI Pattern                     Controller#Action
#     restaurants GET    /restaurants(.:format)          restaurants#index
#                 POST   /restaurants(.:format)          restaurants#create
#  new_restaurant GET    /restaurants/new(.:format)      restaurants#new
# edit_restaurant GET    /restaurants/:id/edit(.:format) restaurants#edit
#      restaurant GET    /restaurants/:id(.:format)      restaurants#show
#                 PATCH  /restaurants/:id(.:format)      restaurants#update
#                 DELETE /restaurants/:id(.:format)      restaurants#destroy

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORIES = %w(chinese italian french belgian japanese)

  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: CATEGORIES }

  def rating
    reviews.average(:rating)
  end



end

app/models/review.rb
class Review < ApplicationRecord

  belongs_to :restaurant
  validates :rating, numericality: { only_integer: true, greater_than_or_equal_to: 0, lesser_than_or_equal_to: 5 }, presence: true
  validates :content, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]


  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def show
    @restaurant = Restaurant.find(params[:id])

  #  assigns the requested restaurant as @restaurant (FAILED - 1)

  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_path
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end

  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  private

  def restaurant_params
      # *Strong params*: You need to *whitelist* what can be updated by the user
      # Never trust user data!

      params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
  # we need @restaurant in our `simple_form_for`
  @restaurant = Restaurant.find(params[:restaurant_id])
  @review = Review.new
  end

  def update
    @review = Review.find(params[:id])
    @review.update(review_params)
    redirect_to review_path(@review)
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to reviews_path
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant

    if @review.save
      redirect_to restaurants_path(@restaurant)
    else
      render :new
    end
  end

  def edit
    @review = Review.find(params[:id])
  end

private

def review_params
params.require(:review).permit(:content, :rating)
end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  </head>

  <body>
<!-- navbar -->

  <div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to restaurants_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "https://vivaspot.com/wp-content/uploads/2016/09/Yelp_Logo_07-300x300.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>

    <!-- Notification -->
    <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
      <div class="badge-container">
        <i class="fa fa-envelope-o"></i>
        <div class="badge badge-blue">3</div>
      </div>
    <% end %>

    <!-- Profile picture and dropdown -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>

    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "Post stuff"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>










  <!-- yield -->
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>

<div class="col-sm-8 col-sm-offset-2">
<% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-group">
  <%= f.label :name%>
  <%= f.text_field :name, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.label :address %>
  <%= f.text_area :address, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.label :phone_number %>
  <%= f.text_area :phone_number, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.label :category %>
  <%= f.text_area :category, class: "form-control" %>
</div>

  <%= f.submit "Update", class: "btn btn-primary" %>

<% end %>
</div>
</div>

app/views/restaurants/create.html.erb
<h1>Restaurants#create</h1>
<p>Find me in app/views/restaurants/create.html.erb</p>

app/views/restaurants/destroy.html.erb
<h1>Restaurants#destroy</h1>
<p>Find me in app/views/restaurants/destroy.html.erb</p>

app/views/restaurants/edit.html.erb
<div class="col-sm-8 col-sm-offset-2">
<h2>Edit a Restaurant</h2>
</div>
<%= render 'form' %>

app/views/restaurants/index.html.erb
<div class="col-sm-8 col-sm-offset-2">
<br>
<br>
<h3>All Restaurants</h3>
<br>
   <%= link_to new_restaurant_path(@restaurant) do %>
      ADD A NEW RESTAURANT!</i></h1>
    <%end%>
<br>
<br>

  <%@restaurants.each do |restaurant| %>
    <%= link_to restaurant.name, restaurant_path(restaurant) %> <%= restaurant.category %>
  <p><%= restaurant.address %></p>
  <p><small><i class="fa fa-phone"></i>   </small><%= restaurant.phone_number %></p>

  <p>Rating:</p>
  <%= restaurant.rating %>
  <p>Content:</p>
  <hr>
<%end%>
<br>
<br>
</div>

app/views/restaurants/new.html.erb
<div class="col-sm-8 col-sm-offset-2">
<h2>New Restaurants</h2>
</div>
<%= render 'form' %>

app/views/restaurants/show.html.erb
<div class="col-sm-8 col-sm-offset-2">
<br>
<br><br>

    <h1><%= @restaurant.name %></h1>
    <p><%= @restaurant.address %></p>


    <%= link_to restaurant_path(@restaurant),
      method: :delete,
      data: { confirm: "Are you sure?" } do %>
      <i class="fa fa-trash-o"></i>
    <%end%>

    <%= link_to edit_restaurant_path(@restaurant) do %>
      <i class="fa fa-pencil"></i></h1>
    <%end%>

    <%= link_to new_restaurant_review_path(@restaurant) do %>
      Add a review!</i></h1>
    <%end%>

  <hr>

  </div>

app/views/restaurants/update.html.erb
<h1>Restaurants#update</h1>
<p>Find me in app/views/restaurants/update.html.erb</p>

app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>

<div class="col-sm-8 col-sm-offset-2">
<% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-group">
  <%= f.label :name%>
  <%= f.text_field :name, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.label :address %>
  <%= f.text_area :address, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.label :phone_number %>
  <%= f.text_area :phone_number, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.label :category %>
  <%= f.text_area :category, class: "form-control" %>
</div>

  <%= f.submit "Update", class: "btn btn-primary" %>

<% end %>
</div>
</div>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

app/views/reviews/edit.html.erb
<h1>Reviews#edit</h1>
<p>Find me in app/views/reviews/edit.html.erb</p>

app/views/reviews/new.html.erb
<div class="col-sm-8 col-sm-offset-2">
<h2>New Reviews</h2>
</div>
<%= render 'form' %>

app/views/reviews/update.html.erb
<h1>Reviews#update</h1>
<p>Find me in app/views/reviews/update.html.erb</p>